name: Check Embassy Slot

on:
  schedule:
    # Понедельник-четверг: утро
    - cron: '*/5 6-10 * * 1-4'
    # Понедельник-четверг: день
    - cron: '*/5 11-14 * * 1-4'
    - cron: '*/5 14 * * 1-4'  # отдельно 14:00-14:30

    # Пятница: утро
    - cron: '*/5 6-10 * * 5'
    # Пятница: день
    - cron: '*/5 11 * * 5'

  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          PYTHONUNBUFFERED: 1
        run: |
          python main.py
