name: Check Embassy Slot

on:
  schedule:
    # 07:45–09:00 по Белграду (05:45–07:00 UTC), каждые 5 минут
    - cron: '45,50,55 5 * * *'
    - cron: '0,5,10,15,20,25,30,35,40,45,50,55 6 * * *'
    - cron: '0 7 * * *'

    # 09:00–11:00 по Белграду (07:00–09:00 UTC), каждые 10 минут
    - cron: '0,10,20,30,40,50 7 * * *'
    - cron: '0,10,20,30,40,50 8 * * *'

    # 11:00–14:30 по Белграду (09:00–12:30 UTC), каждые 15 минут
    - cron: '0,15,30,45 9 * * *'
    - cron: '0,15,30,45 10 * * *'
    - cron: '0,15,30,45 11 * * *'
    - cron: '0,15,30 12 * * *'

  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    name: "Check Embassy Slot - Run at ${{ github.event.repository.updated_at }}"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get current time
        id: get-time
        run: echo "current_time=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Run script
        env:
          PYTHONUNBUFFERED: 1
        run: |
          python main.py
