name: Check Embassy Slot

on:
  schedule:
    # 05:40–05:58 UTC (07:40–07:58 по Белграду)
    - cron: '40,42,44,46,48,50,52,54,56,58 5 * * 1-5'

    # 06:00–14:58 UTC (08:00–16:58 по Белграду)
    - cron: '*/2 6-14 * * 1-5'

    # 15:00 UTC (17:00 по Белграду)
    - cron: '0 15 * * 1-5'

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    name: "Check Embassy Slot - Run at ${{ github.event.repository.updated_at }}"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get current time
        id: get-time
        run: echo "current_time=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Run script
        env:
          PYTHONUNBUFFERED: 1
        run: |
          python main.py
