name: Check Embassy Slot

on:
  schedule:
    # Понедельник – Четверг

    # Утро: 07:40–10:00 по Белграду, каждые 5 минут
    - cron: '40-59/5 5 * * 1-4'
    - cron: '*/5 6-7 * * 1-4'
    - cron: '0,5,10,15,20,25,30,35,40,45,50,55 8 * * 1-4'

    # Утро: 10:00–12:00 по Белграду, каждые 10 минут
    - cron: '*/10 8-9 * * 1-4'

    # День: 13:00–16:30 по Белграду, каждые 15 минут
    - cron: '0,15,30,45 11-13 * * 1-4'
    - cron: '0,15,30 14 * * 1-4'

    # Пятница

    # Утро: 07:40–10:00 по Белграду, каждые 5 минут
    - cron: '40-59/5 5 * * 5'
    - cron: '*/5 6-7 * * 5'
    - cron: '0,5,10,15,20,25,30,35,40,45,50,55 8 * * 5'

    # Утро: 10:00–12:00 по Белграду, каждые 10 минут
    - cron: '*/10 8-9 * * 5'

    # День: 13:00–14:00 по Белграду, каждые 15 минут
    - cron: '0,15,30,45 11 * * 5'

  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    name: "Check Embassy Slot - Run at ${{ github.event.repository.updated_at }}"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get current time
        id: get-time
        run: echo "current_time=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Run script
        env:
          PYTHONUNBUFFERED: 1
        run: |
          python main.py
